import { XCLSR_BTSTRP_EDITOR_PREFIX } from '../../constants';
export const ALLOWED_BLOCKS = [
    XCLSR_BTSTRP_EDITOR_PREFIX + "/homepage-content",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/accordion",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/buttons",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/image-banner",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/horizontal-rule",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/iframe-embed",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/start-here-banner",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/callout",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/tipbox",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/columns",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/cards",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/image-and-text",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/image",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/code-block",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/task-group",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/tabs",
    XCLSR_BTSTRP_EDITOR_PREFIX + "/page-navigation",
    "core/paragraph",
    "core/heading",
    "core/list",
    "core/table",
    "core/freeform",
    "core/html"
];